name: Large size test

on:
  workflow_call:

jobs:
  test-large:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup OpenAPI generator
        run: |
          npm install -g @openapitools/openapi-generator-cli
      - name: Setup test
        run: |
          openapi-generator-cli generate -i https://raw.githubusercontent.com/toms74209200/openapi-todo-example/refs/heads/master/reference/spec.yaml -g python -o ./e2etest/openapi_gen
          cd e2etest/openapi_gen
          pip install -r requirements.txt
          pip install setuptools
          python setup.py install --user
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r server/requirements.txt
          pip install -r e2etest/requirements.txt
      - name: Launch server
        run: PYTHONPATH=src uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080 &
        working-directory: server
      - name: Run tests
        run: pytest tests/ -v
        working-directory: e2etest
